# Generated by Django 3.2 on 2022-11-02 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapplications', '0002_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
                ('app_made_on', models.DateField(auto_now_add=True, verbose_name='Appointment Booking Date')),
                ('app_fix_date', models.DateField(verbose_name='Appointment Date')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='myapplications.doctor', verbose_name='Doctor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL, verbose_name='Patient')),
            ],
        ),
    ]
