# Generated by Django 3.2 on 2022-11-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapplications', '0004_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='app_fix_date',
            field=models.DateField(blank=True, verbose_name='Appointment Date'),
        ),
    ]
